#!/usr/bin/env bash
# Installs the Android SDK + NDK needed to build Anti-FOMO for Android.
#
# The Rust Android targets and a JDK are prerequisites; this script only
# handles the SDK side. Everything lands under $ANDROID_HOME (default
# /mnt/dellhdd/android-sdk) rather than ~/Android, because a full SDK + NDK is
# ~8-10 GB and the system disk does not have room.
#
# After running, source scripts/android-env.sh (written by this script) or add
# its exports to your shell profile.

set -euo pipefail

ANDROID_HOME="${ANDROID_HOME:-/mnt/dellhdd/android-sdk}"
# Must match compileSdk/targetSdk in the generated
# app/src-tauri/gen/android/app/build.gradle.kts, or Gradle downloads the right
# platform itself on first build. Bump deliberately, not automatically.
PLATFORM="android-36"
BUILD_TOOLS="36.0.0"
NDK_VERSION="27.2.12479018"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CMDLINE_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"

echo "==> Installing Android SDK to $ANDROID_HOME"
mkdir -p "$ANDROID_HOME"

if [ ! -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
  echo "==> Downloading command-line tools"
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  curl -fsSL -o "$tmp/cmdline-tools.zip" "$CMDLINE_TOOLS_URL"
  unzip -q "$tmp/cmdline-tools.zip" -d "$tmp"
  # sdkmanager insists on living at cmdline-tools/latest/.
  mkdir -p "$ANDROID_HOME/cmdline-tools"
  rm -rf "$ANDROID_HOME/cmdline-tools/latest"
  mv "$tmp/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"
else
  echo "==> Command-line tools already present"
fi

export ANDROID_HOME
export ANDROID_SDK_ROOT="$ANDROID_HOME"
SDKMANAGER="$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"

echo "==> Accepting licenses"
yes | "$SDKMANAGER" --licenses > /dev/null 2>&1 || true

echo "==> Installing platform-tools, $PLATFORM, build-tools $BUILD_TOOLS, NDK $NDK_VERSION"
"$SDKMANAGER" --install \
  "platform-tools" \
  "platforms;$PLATFORM" \
  "build-tools;$BUILD_TOOLS" \
  "ndk;$NDK_VERSION"

cat > "$REPO_ROOT/scripts/android-env.sh" <<EOF
# Source this before running \`npm run tauri android ...\`.
# Generated by scripts/setup-android.sh — safe to regenerate.
export ANDROID_HOME="$ANDROID_HOME"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export NDK_HOME="$ANDROID_HOME/ndk/$NDK_VERSION"
export ANDROID_NDK_HOME="\$NDK_HOME"
export JAVA_HOME="\${JAVA_HOME:-/usr/lib/jvm/java-17-openjdk}"
export PATH="\$ANDROID_HOME/platform-tools:\$ANDROID_HOME/cmdline-tools/latest/bin:\$PATH"
EOF

echo
echo "==> Done. Next:"
echo "    source scripts/android-env.sh"
echo "    cd app && npm run tauri android init"
echo "    npm run tauri android dev      # with a device attached via adb"
